from app.models.agent_state import AgentState
from app.services.plan_parser_service import PlanParserService
from app.services.planner_service import PlannerService
from app.services.answer_generation_service import AnswerGenerationService
from app.services.reflection_service import ReflectionService
from app.services.step_executor_service import StepExecutorService


class PlannerExecutorService:

    @staticmethod
    def execute(
            question: str
    ):

        """
        Main agent orchestration service.

        Responsibilities
        ----------------
        1. Create an execution plan.
        2. Parse the plan into executable steps.
        3. Execute each step.
        4. Collect observations from tools.
        5. Evaluate collected observations.
        6. Generate the final answer.

        This service acts as the central coordinator
        for the Planner-Executor workflow.

        Workflow
        --------
        User Question
                ↓
            Planner
                ↓
         Plan Parser
                ↓
        Step Executor
                ↓
         Observations
                ↓
          Reflection
                ↓
         Final Answer
        """

        # ==================================================
        # AGENT STATE
        #
        # AgentState stores all runtime information
        # throughout the execution lifecycle.
        # ==================================================

        state = AgentState(
            question=question
        )

        # ==================================================
        # PLANNER PHASE
        #
        # Create a high-level execution strategy
        # for answering the user's question.
        #
        # Example:
        #
        # 1. Search Memory
        # 2. Search PDF
        # 3. Generate Answer
        #
        # The planner decides WHAT should be done.
        # ==================================================

        state.plan = (
            PlannerService.create_plan(
                state.question
            )
        )

        print("\nPLAN")
        print(state.plan)

        # ==================================================
        # PLAN PARSING PHASE
        #
        # Convert planner output into a list
        # of executable steps.
        #
        # Example:
        #
        # Planner Output:
        #
        # 1. Search Memory
        # 2. Search PDF
        #
        # Parsed Output:
        #
        # [
        #     "Search Memory",
        #     "Search PDF"
        # ]
        # ==================================================

        plan_steps = (
            PlanParserService.parse(
                state.plan
            )
        )

        print("\nPLAN STEPS")

        for step in plan_steps:
            print(step)

        # ==================================================
        # EXECUTION PHASE
        #
        # Execute every step generated by
        # the planner.
        #
        # Step execution updates:
        #
        # - current_step
        # - completed_steps
        # - observation
        #
        # Tool outputs accumulate inside
        # state.observation.
        # ==================================================

        for step in plan_steps:

            if (
                    step.upper()
                    ==
                    "GENERATE ANSWER"
            ):
                continue

            state = (
                StepExecutorService.execute_step(
                    state,
                    step
                )
            )

        # ==================================================
        # OBSERVATION SUMMARY
        #
        # All planned steps have completed.
        #
        # The collected observations represent
        # everything discovered during execution.
        # ==================================================

        print("\nFINAL OBSERVATION FROM PLAN")

        for item in state.observation:
            print(item)

        # ==================================================
        # REFLECTION PHASE
        #
        # Reflection acts as an evaluator.
        #
        # It determines whether the collected
        # observations contain enough information
        # to answer the user's question.
        #
        # Expected Values:
        #
        # ENOUGH
        #
        # or
        #
        # NEED_MORE_INFORMATION
        # ==================================================

        state.reflection = (
            ReflectionService.evaluate(
                question=state.question,
                observation=state.observation
            )
        )

        print("\nREFLECTION")
        print(state.reflection)

        # ==================================================
        # ANSWER GENERATION
        #
        # Generate the final answer only when
        # sufficient information is available.
        # ==================================================

        if (
                state.reflection
                and
                state.reflection.strip().upper()
                == "ENOUGH"
        ):

            state.answer = (
                AnswerGenerationService.generate_answer(
                    question=state.question,
                    observation=state.observation
                )
            )

        else:

            state.answer = (
                "I could not find enough "
                "information to answer "
                "the question."
            )

        print("\nFINAL ANSWER")
        print(state.answer)

        # ==================================================
        # RESPONSE PAYLOAD
        #
        # Return execution details for
        # API consumers, debugging,
        # tracing, and future UI support.
        # ==================================================

        return {
            "plan": state.plan,
            "current_step": state.current_step,
            "completed_steps": state.completed_steps,
            "observation": state.observation,
            "reflection": state.reflection,
            "answer": state.answer
        }