from app.models.agent_state import AgentState
from app.services.plan_parser_service import PlanParserService
from app.services.planner_service import PlannerService
from app.services.answer_generation_service import AnswerGenerationService
from app.services.reflection_service import ReflectionService
from app.services.step_executor_service import StepExecutorService
from app.services.replan_service import ReplanService


class PlannerExecutorService:

    @staticmethod
    def _execute_plan(
            state: AgentState
    ):
        """
        Executes every step generated by
        the planner.

        Responsibilities
        ----------------
        1. Parse the execution plan.
        2. Execute every planner step.
        3. Collect observations from tools.
        4. Track execution progress.

        This helper allows the same execution
        logic to be reused during replanning.
        """

        # Convert the planner output into
        # executable steps.
        plan_steps = (
            PlanParserService.parse(
                state.plan
            )
        )

        print("\nPLAN STEPS")

        for step in plan_steps:
            print(step)

        # Execute every planner step except
        # the final answer generation step.
        for step in plan_steps:

            if step.upper() == "GENERATE ANSWER":
                continue

            state = (
                StepExecutorService.execute_step(
                    state,
                    step
                )
            )

        print("\nFINAL OBSERVATION FROM PLAN")

        for item in state.observation:
            print(item)

        return state


    @staticmethod
    def _evaluate_reflection(
            state: AgentState
    ):
        """
        Evaluates whether the collected
        observations are sufficient to
        answer the user's question.
        """

        state.reflection = (
            ReflectionService.evaluate(
                question=state.question,
                observation=state.observation
            )
        )

        print("\nREFLECTION")
        print(state.reflection)

        return state

    @staticmethod
    def _replan(
            state: AgentState
    ):
        """
        Creates a new execution plan when the
        previous plan failed to gather enough
        information.

        Responsibilities
        ----------------
        1. Increment replanning attempts.
        2. Generate a new execution plan.
        3. Execute the new plan.
        4. Re-evaluate the new observations.
        """

        state.replan_count += 1

        print(
            f"\nREPLAN ATTEMPT: "
            f"{state.replan_count}"
        )

        state.plan = (
            ReplanService.create_replan(
                question=state.question,
                observation=state.observation
            )
        )

        print("\nNEW PLAN")
        print(state.plan)

        state = (
            PlannerExecutorService._execute_plan(
                state
            )
        )

        state = (
            PlannerExecutorService._evaluate_reflection(
                state
            )
        )

        return state

    @staticmethod
    def execute(
            question: str
    ):

        """
        Main agent orchestration service.

        Responsibilities
        ----------------
        1. Create an execution plan.
        2. Parse the plan into executable steps.
        3. Execute each step.
        4. Collect observations from tools.
        5. Evaluate collected observations.
        6. Generate the final answer.

        This service acts as the central coordinator
        for the Planner-Executor workflow.

        Workflow
        --------
        User Question
                ↓
            Planner
                ↓
         Plan Parser
                ↓
        Step Executor
                ↓
         Observations
                ↓
          Reflection
                ↓
         Final Answer
        """

        # ==================================================
        # AGENT STATE
        #
        # AgentState stores all runtime information
        # throughout the execution lifecycle.
        # ==================================================

        state = AgentState(
            question=question
        )

        # Maximum replanning attempts.
        max_replans = 1

        # ==================================================
        # PLANNER PHASE
        #
        # Create a high-level execution strategy
        # for answering the user's question.
        #
        # Example:
        #
        # 1. Search Memory
        # 2. Search PDF
        # 3. Generate Answer
        #
        # The planner decides WHAT should be done.
        # ==================================================

        state.plan = (
            PlannerService.create_plan(
                state.question
            )
        )

        print("\nPLAN")
        print(state.plan)

        # ==================================================
        # PLAN EXECUTION PHASE
        #
        # Execute the complete planner workflow.
        #
        # Responsibilities:
        #
        # - Parse the execution plan
        # - Execute every planner step
        # - Collect observations
        #
        # The implementation is delegated to
        # _execute_plan() so the same execution
        # logic can be reused during replanning.
        # ==================================================

        state = (
            PlannerExecutorService._execute_plan(
                state
            )
        )

        # ==================================================
        # REFLECTION PHASE
        #
        # Reflection acts as an evaluator.
        #
        # It determines whether the collected
        # observations contain enough information
        # to answer the user's question.
        #
        # Expected Values:
        #
        # ENOUGH
        #
        # or
        #
        # NEED_MORE_INFORMATION
        # ==================================================

        state = (
            PlannerExecutorService._evaluate_reflection(
                state
            )
        )

        # ==================================================
        # ANSWER GENERATION
        #
        # Generate the final answer only when
        # sufficient information is available.
        # ==================================================

        while (
                state.reflection.strip().upper()
                != "ENOUGH"
                and
                state.replan_count < max_replans
        ):
            state = (
                PlannerExecutorService._replan(
                    state
                )
            )

        if (
                state.reflection
                and
                state.reflection.strip().upper()
                == "ENOUGH"
        ):

            state.answer = (
                AnswerGenerationService.generate_answer(
                    question=state.question,
                    observation=state.observation
                )
            )

        else:

            state.answer = (
                "I could not find enough "
                "information to answer "
                "the question."
            )

        print("\nFINAL ANSWER")
        print(state.answer)

        # ==================================================
        # RESPONSE PAYLOAD
        #
        # Return execution details for
        # API consumers, debugging,
        # tracing, and future UI support.
        # ==================================================

        return {
            "plan": state.plan,
            "current_step": state.current_step,
            "completed_steps": state.completed_steps,
            "observation": state.observation,
            "reflection": state.reflection,
            "answer": state.answer
        }