"""
Purpose
-------
When an agent fails to answer a question correctly,
we do not want it to blindly repeat the exact same
reasoning process.

This service builds a retry prompt that contains:

1. Original Question
2. Previous Action
3. Previous Observation
4. Reflection Result

This gives the agent visibility into its previous
failure so it can potentially choose a different
strategy during the next attempt.

Without this service:

Attempt 1 -> Memory Tool
Attempt 2 -> Memory Tool Again

With this service:

Attempt 1 -> Memory Tool
Reflection -> Not Enough Information
Attempt 2 -> Agent Knows Previous Attempt Failed
"""

class RetryPromptService:

    @staticmethod
    def build(
            question: str,
            action: str,
            observation: list,
            reflection: str
    ):
        """
              Builds a retry prompt for the next agent iteration.

              Parameters
              ----------
              question:
                  Original user question.

              action:
                  Tool selected during previous attempt.

              observation:
                  Output returned by the selected tool.

              reflection:
                  Evaluation result generated by ReflectionService.

              Returns
              -------
              A richer prompt that provides context about
              the previous failed attempt.
              """

        return f"""
        Original Question:
        {question}

        Previous Action:
        {action}

        Previous Observation:
        {observation}

        Reflection Result:
        {reflection}

        The previous attempt did not provide enough information.

        Think again and choose the best action.
        """