from app.models.agent_state import AgentState
from app.tools.tool_registry import TOOL_REGISTRY


class StepExecutorService:

    @staticmethod
    def execute_step(
            state: AgentState,
            step: str
    ):
        """
        Executes a single step generated by
        the Planner.

        Responsibilities
        ----------------
        1. Identify the tool associated with
           the planner step.

        2. Retrieve the tool from the
           Tool Registry.

        3. Execute the selected tool.

        4. Store tool output inside
           AgentState.observation.

        5. Track execution progress using:

           - current_step
           - completed_steps

        Architecture
        ------------
        Planner Step
                ↓
          Tool Registry
                ↓
             Tool
                ↓
           Observation

        Example
        -------
        Planner Step:

        Search Memory

        Registry Lookup:

        TOOL_REGISTRY["SEARCH MEMORY"]

        Resolved Tool:

        MemoryTool

        Execution:

        MemoryTool.execute(question)
        """

        # Track the currently executing step.
        state.current_step = step

        print(
            f"\nEXECUTING STEP: {step}"
        )

        # ==================================================
        # TOOL REGISTRY LOOKUP
        #
        # Retrieve the tool associated with
        # the planner step.
        #
        # Example:
        #
        # SEARCH MEMORY -> MemoryTool
        # SEARCH PDF    -> PdfTool
        # ==================================================

        tool = TOOL_REGISTRY.get(
            step.upper()
        )

        # ==================================================
        # TOOL EXECUTION
        #
        # Execute the selected tool and
        # append results to observations.
        # ==================================================

        if tool:

            result = (
                tool.execute(
                    state.question
                )
            )

            state.observation.extend(
                result
            )

        # ==================================================
        # STEP TRACKING
        #
        # Record successful execution
        # of the planner step.
        # ==================================================

        state.completed_steps.append(
            step
        )

        print(
            f"\nCOMPLETED STEPS: "
            f"{state.completed_steps}"
        )

        return state