from pydantic import BaseModel, Field


class AgentState(BaseModel):
    """
    Stores the complete runtime state
    for a Planner-Executor workflow.
    """

    # Original user question.
    question: str

    # Plan generated by PlannerService.
    plan: str | None = None

    # Currently executing step.
    current_step: str | None = None

    # Completed plan steps.
    completed_steps: list = Field(
        default_factory=list
    )

    # Aggregated tool outputs.
    observation: list = Field(
        default_factory=list
    )

    # Reflection result.
    reflection: str | None = None

    # Final answer generated for user.
    answer: str | None = None